language: r
sudo: true
cache: packages

os:
  - linux

before_script:
 - sudo apt-get install r-base-core
scrpit:
  - Rscrpit R/makeDashboard.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master
