language: r
sudo: false
cache: packages
os:
  - linux

scrpit:
  - Rscript R/01_get_raw_data.R
  - Rscript R/02_get_Stage1_data.R
  - Rscript R/03_make_pred.R
  - Rscript R/04_makeDashboard.R

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: master